package com.chinaex123.redstone_enchants.init;

import com.chinaex123.redstone_enchants.RedstoneEnchants;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceKey;
import net.minecraft.world.item.enchantment.Enchantment;
import net.neoforged.bus.api.IEventBus;

/**
 * 模组附魔的 ResourceKey 常量表。附魔本体是数据包条目，由 {@code data/ModEnchantmentProvider} 生成。
 */
public final class ModEnchantments {
    public static final ResourceKey<Enchantment> ACCURACY_SHOT = key("accuracy_shot");
    public static final ResourceKey<Enchantment> ADAPTIVE = key("adaptive");
    public static final ResourceKey<Enchantment> ADVANCED_UNBREAKING = key("advanced_unbreaking");
    public static final ResourceKey<Enchantment> AGAINST_ALL_ODDS = key("against_all_odds");
    public static final ResourceKey<Enchantment> ANGLER = key("angler");
    public static final ResourceKey<Enchantment> AMBUSH = key("ambush");
    public static final ResourceKey<Enchantment> ANTI_CAMOUFLAGE = key("anti_camouflage");
    public static final ResourceKey<Enchantment> AURA_BURNING = key("aura_burning");
    public static final ResourceKey<Enchantment> AURA_GLOWING = key("aura_glowing");
    public static final ResourceKey<Enchantment> AURA_HASTE = key("aura_haste");
    public static final ResourceKey<Enchantment> AURA_INFESTED = key("aura_infested");
    public static final ResourceKey<Enchantment> AURA_JUMP_BOOST = key("aura_jump_boost");
    public static final ResourceKey<Enchantment> AURA_POISON = key("aura_poison");
    public static final ResourceKey<Enchantment> AURA_REGENERATION = key("aura_regeneration");
    public static final ResourceKey<Enchantment> AURA_RESISTANCE = key("aura_resistance");
    public static final ResourceKey<Enchantment> AURA_SLOWNESS = key("aura_slowness");
    public static final ResourceKey<Enchantment> AURA_SPEED = key("aura_speed");
    public static final ResourceKey<Enchantment> AURA_STRENGTH = key("aura_strength");
    public static final ResourceKey<Enchantment> AURA_WEAKNESS = key("aura_weakness");
    public static final ResourceKey<Enchantment> AURA_WITHER = key("aura_wither");
    public static final ResourceKey<Enchantment> AUTO_SMELT = key("auto_smelt");
    public static final ResourceKey<Enchantment> BACKSTAB = key("backstab");
    public static final ResourceKey<Enchantment> BANE_BADY = key("bane_bady");
    public static final ResourceKey<Enchantment> BANE_BOSS = key("bane_boss");
    public static final ResourceKey<Enchantment> BANE_END = key("bane_end");
    public static final ResourceKey<Enchantment> BANE_ILLAGER = key("bane_illager");
    public static final ResourceKey<Enchantment> BANE_NETHER = key("bane_nether");
    public static final ResourceKey<Enchantment> BANE_PHANTOM = key("bane_phantom");
    public static final ResourceKey<Enchantment> BANE_WATER = key("bane_water");
    public static final ResourceKey<Enchantment> BERSERK = key("berserk");
    public static final ResourceKey<Enchantment> BOONS = key("boons");
    public static final ResourceKey<Enchantment> BOLTBRINGER = key("boltbringer");
    public static final ResourceKey<Enchantment> BLAST_ARROWS = key("blast_arrows");
    public static final ResourceKey<Enchantment> BOMB_ARROWS = key("bomb_arrows");
    public static final ResourceKey<Enchantment> BULLET_TIME = key("bullet_time");
    public static final ResourceKey<Enchantment> BULLETPROOF = key("bulletproof");
    public static final ResourceKey<Enchantment> BUTCHER = key("butcher");
    public static final ResourceKey<Enchantment> CALAMITY = key("calamity");
    public static final ResourceKey<Enchantment> CARRION_EATER = key("carrion_eater");
    public static final ResourceKey<Enchantment> CHAIN_HASTE = key("chain_haste");
    public static final ResourceKey<Enchantment> CHAIN_REACTION = key("chain_reaction");
    public static final ResourceKey<Enchantment> CHAINS = key("chains");
    public static final ResourceKey<Enchantment> CONDUCTIVE_LINE = key("conductive_line");
    public static final ResourceKey<Enchantment> CROP_DANCE = key("crop_dance");
    public static final ResourceKey<Enchantment> CURSE_OF_RUST = key("curse_of_rust");
    public static final ResourceKey<Enchantment> CURSE_OF_ACROPHOBIA = key("curse_of_acrophobia");
    public static final ResourceKey<Enchantment> CURSE_OF_BASIPHOBIA = key("curse_of_basiphobia");
    public static final ResourceKey<Enchantment> CURSE_OF_BLINDNESS = key("curse_of_blindness");
    public static final ResourceKey<Enchantment> CURSE_OF_GRAVITY = key("curse_of_gravity");
    public static final ResourceKey<Enchantment> CURSE_OF_HUNGER = key("curse_of_hunger");
    public static final ResourceKey<Enchantment> CURSE_OF_UNLUCKY = key("curse_of_unlucky");
    public static final ResourceKey<Enchantment> CURSE_OF_BLAST = key("curse_of_blast");
    public static final ResourceKey<Enchantment> CURSE_OF_STILLNESS = key("curse_of_stillness");
    public static final ResourceKey<Enchantment> CURSE_OF_VULNERABILITY = key("curse_of_vulnerability");
    public static final ResourceKey<Enchantment> CURSE_OF_WATER_SOURCE = key("curse_of_water_source");
    public static final ResourceKey<Enchantment> DAYNIGHT_CYCLE = key("daynight_cycle");
    public static final ResourceKey<Enchantment> DECAPITATION = key("decapitation");
    public static final ResourceKey<Enchantment> DESPERATE_COUNTER = key("desperate_counter");
    public static final ResourceKey<Enchantment> DEVOURING = key("devouring");
    public static final ResourceKey<Enchantment> DANGEROUS_EDGE = key("dangerous_edge");
    public static final ResourceKey<Enchantment> DYNAMO = key("dynamo");
    public static final ResourceKey<Enchantment> ECHOES_BATTLE = key("echoes_battle");
    public static final ResourceKey<Enchantment> ENDLESS_WOOL = key("endless_wool");
    public static final ResourceKey<Enchantment> EXOSKELETON = key("exoskeleton");
    public static final ResourceKey<Enchantment> EQUALIZER = key("equalizer");
    public static final ResourceKey<Enchantment> EXCAVATOR = key("excavator");
    public static final ResourceKey<Enchantment> EXECUTION = key("execution");
    public static final ResourceKey<Enchantment> EXPERIENCE_SHEAR = key("experience_shear");
    public static final ResourceKey<Enchantment> FATAL_ARROW = key("fatal_arrow");
    public static final ResourceKey<Enchantment> FIRE_ARROWS = key("fire_arrows");
    public static final ResourceKey<Enchantment> FIRE_PROTECTION = key("fire_protection");
    public static final ResourceKey<Enchantment> FORTITUDE = key("fortitude");
    public static final ResourceKey<Enchantment> FURY = key("fury");
    public static final ResourceKey<Enchantment> FOCUS = key("focus");
    public static final ResourceKey<Enchantment> FLAME_WALKER = key("flame_walker");
    public static final ResourceKey<Enchantment> GAMBLER = key("gambler");
    public static final ResourceKey<Enchantment> GEOLOGY = key("geology");
    public static final ResourceKey<Enchantment> GALLOP = key("gallop");
    public static final ResourceKey<Enchantment> GALLOP_END = key("gallop_end");
    public static final ResourceKey<Enchantment> GALLOP_SAND = key("gallop_sand");
    public static final ResourceKey<Enchantment> GLASS_BREAKER = key("glass_breaker");
    public static final ResourceKey<Enchantment> GOLDFINGER = key("goldfinger");
    public static final ResourceKey<Enchantment> HARVEST_ECHO = key("harvest_echo");
    public static final ResourceKey<Enchantment> HASTE = key("haste");
    public static final ResourceKey<Enchantment> ICE_ARROWS = key("ice_arrows");
    public static final ResourceKey<Enchantment> INDESTRUCTIBLE = key("indestructible");
    public static final ResourceKey<Enchantment> JUMP_AMPLIFIER = key("jump_amplifier");
    public static final ResourceKey<Enchantment> INVISIBILITY_CLOAK = key("invisibility_cloak");
    public static final ResourceKey<Enchantment> LIFE_STEAL = key("life_steal");
    public static final ResourceKey<Enchantment> LUCKY_BOOST = key("lucky_boost");
    public static final ResourceKey<Enchantment> LUCKY_LIGHT = key("lucky_light");
    public static final ResourceKey<Enchantment> MAGNET = key("magnet");
    public static final ResourceKey<Enchantment> MASTER_GATHERER = key("master_gatherer");
    public static final ResourceKey<Enchantment> MAXIMIZATION = key("maximization");
    public static final ResourceKey<Enchantment> MINIFY = key("minify");
    public static final ResourceKey<Enchantment> MOIST = key("moist");
    public static final ResourceKey<Enchantment> NULLIFY = key("nullify");
    public static final ResourceKey<Enchantment> PACK_LEADER = key("pack_leader");
    public static final ResourceKey<Enchantment> PASTURE = key("pasture");
    public static final ResourceKey<Enchantment> PEGASUS = key("pegasus");
    public static final ResourceKey<Enchantment> PRESERVATION = key("preservation");
    public static final ResourceKey<Enchantment> POTENTIAL_CONVERSION = key("potential_conversion");
    public static final ResourceKey<Enchantment> PROTECTION_DAY = key("protection_day");
    public static final ResourceKey<Enchantment> PROTECTION_END = key("protection_end");
    public static final ResourceKey<Enchantment> PROTECTION_NETHER = key("protection_nether");
    public static final ResourceKey<Enchantment> PROTECTION_NIGHT = key("protection_night");
    public static final ResourceKey<Enchantment> RAIN_DRIPSTONE = key("rain_dripstone");
    public static final ResourceKey<Enchantment> RAIN_FORGE = key("rain_forge");
    public static final ResourceKey<Enchantment> RAPID = key("rapid");
    public static final ResourceKey<Enchantment> RESILIENCE_SHIELD = key("resilience_shield");
    public static final ResourceKey<Enchantment> RICOCHET = key("ricochet");
    public static final ResourceKey<Enchantment> REVIVE_WARD = key("revive_ward");
    public static final ResourceKey<Enchantment> SACRIFICE = key("sacrifice");
    public static final ResourceKey<Enchantment> SCATTER = key("scatter");
    public static final ResourceKey<Enchantment> SEA_BREEZE = key("sea_breeze");
    public static final ResourceKey<Enchantment> SEARING = key("searing");
    public static final ResourceKey<Enchantment> SHOTGUN = key("shotgun");
    public static final ResourceKey<Enchantment> SPLASH_BLINDNESS = key("splash_blindness");
    public static final ResourceKey<Enchantment> SPLASH_DELAYED_EXPLOSION = key("splash_delayed_explosion");
    public static final ResourceKey<Enchantment> SPLASH_GLOWING = key("splash_glowing");
    public static final ResourceKey<Enchantment> SPLASH_HUNGER = key("splash_hunger");
    public static final ResourceKey<Enchantment> SPLASH_INFESTED = key("splash_infested");
    public static final ResourceKey<Enchantment> SPLASH_OOZING = key("splash_oozing");
    public static final ResourceKey<Enchantment> SPLASH_POISON = key("splash_poison");
    public static final ResourceKey<Enchantment> SPLASH_REGENERATION = key("splash_regeneration");
    public static final ResourceKey<Enchantment> SPLASH_SLOW_FALLING = key("splash_slow_falling");
    public static final ResourceKey<Enchantment> SPLASH_SLOWNESS = key("splash_slowness");
    public static final ResourceKey<Enchantment> SPLASH_SPEED = key("splash_speed");
    public static final ResourceKey<Enchantment> SPLASH_WEAVING = key("splash_weaving");
    public static final ResourceKey<Enchantment> SPLASH_WIND_CHARGED = key("splash_wind_charged");
    public static final ResourceKey<Enchantment> SPLASH_WITHER = key("splash_wither");
    public static final ResourceKey<Enchantment> SHEPHERD = key("shepherd");
    public static final ResourceKey<Enchantment> SWIFT_SHADOWCUTTER = key("swift_shadowcutter");
    public static final ResourceKey<Enchantment> SNIPE = key("snipe");
    public static final ResourceKey<Enchantment> SNOWBALL = key("snowball");
    public static final ResourceKey<Enchantment> SPIRIT = key("spirit");
    public static final ResourceKey<Enchantment> STURDY = key("sturdy");
    public static final ResourceKey<Enchantment> TACTICAL_KNEE = key("tactical_knee");
    public static final ResourceKey<Enchantment> TIDE_SENSE = key("tide_sense");
    public static final ResourceKey<Enchantment> TIMBER = key("timber");
    public static final ResourceKey<Enchantment> TOUCH_BLEEDING = key("touch_bleeding");
    public static final ResourceKey<Enchantment> TOUCH_POISON = key("touch_poison");
    public static final ResourceKey<Enchantment> TOUCH_WITHER = key("touch_wither");
    public static final ResourceKey<Enchantment> TRACKER = key("tracker");
    public static final ResourceKey<Enchantment> UNDERCURRENT = key("undercurrent");
    public static final ResourceKey<Enchantment> UNDER_PRESSURE = key("under_pressure");
    public static final ResourceKey<Enchantment> UNLEASH_POTENTIAL = key("unleash_potential");
    public static final ResourceKey<Enchantment> TRAIL_CHERRY_LEAVES = key("trail_cherry_leaves");
    public static final ResourceKey<Enchantment> TRAIL_DRAGON_BREATH = key("trail_dragon_breath");
    public static final ResourceKey<Enchantment> TRAIL_FIREWORK = key("trail_firework");
    public static final ResourceKey<Enchantment> TRAIL_GLOW = key("trail_glow");
    public static final ResourceKey<Enchantment> TRAIL_SCULK_SOUL = key("trail_sculk_soul");
    public static final ResourceKey<Enchantment> TRAIL_SNOWFLAKE = key("trail_snowflake");
    public static final ResourceKey<Enchantment> TRAIL_TRIAL_OMEN = key("trail_trial_omen");
    public static final ResourceKey<Enchantment> TRAIL_WAX_OFF = key("trail_wax_off");
    public static final ResourceKey<Enchantment> TRAIL_WAX_ON = key("trail_wax_on");
    public static final ResourceKey<Enchantment> VOLT = key("volt");
    public static final ResourceKey<Enchantment> WATER_BOTTLE_PROJECTION = key("water_bottle_projection");
    public static final ResourceKey<Enchantment> WALKER_GRASS = key("walker_grass");
    public static final ResourceKey<Enchantment> WALKER_MAGMA = key("walker_magma");
    public static final ResourceKey<Enchantment> WALKER_SNOWMELT = key("walker_snowmelt");
    public static final ResourceKey<Enchantment> WAVE_WALKER = key("wave_walker");
    public static final ResourceKey<Enchantment> WEAK_ARMOR = key("weak_armor");
    public static final ResourceKey<Enchantment> WEIGHTED = key("weighted");
    public static final ResourceKey<Enchantment> XP_REAPER_MOBS = key("xp_reaper_mobs");

    public static ResourceKey<Enchantment> key(String path) {
        return ResourceKey.create(Registries.ENCHANTMENT, RedstoneEnchants.asResource(path));
    }

    public static void register(IEventBus eventBus) {
        ModEnchantmentEffectComponents.register(eventBus);
        ModEnchantmentEntityEffects.register(eventBus);
        ModEnchantmentLevelBasedValues.register(eventBus);
    }

    private ModEnchantments() {
    }
}
